### ISSUE TITLE
New 2023 models

### ISSUE THREAD

**Issue by gjdonkers** [quacktacular/mac-device-id-to-model#3]
Hi,

We just received the 2023 model `Mac14,5`, these are not in the list but at https://support.apple.com/en-ca/HT201300

Can you update these? I don't use python otherwise I would have made and pr..

Regards

Giedo

**Comment by quacktacular** [comment]
Sure they've been added https://github.com/quacktacular/mac-device-id-to-model/commit/61e7f61a255d87764ae7dc072ace3c34e0e8eccb
