### ISSUE TITLE
MacBookPro15,2

### ISSUE THREAD

**Issue by Alerav** [quacktacular/mac-device-id-to-model#4]
In your text file you have listed 15,2 as a MacBook Pro (13-inch, 2019, Four Thunderbolt 3 ports) when actually it is a 13" MacBook Pro with Thunderbolt 3 and Touch ID (Mid 2018)

Cheers

**Comment by quacktacular** [comment]
Hey @Alerav! The script scrapes Apple's official knowledge base articles for the identifiers and models. Please see https://support.apple.com/en-ca/HT201300 for MacBook Pro.

You will notice MacBookPro15,2 is used for both the mid 2018 and 2019 models. They were probably mostly identical. Apple has reused model identifiers a few times.

For that reason 15,2 is listed for both models in models.txt :) The example script just uses whatever is first in the list, but you could adapt it or write something else to suit your needs (perhaps listing both model names with an `or`)
